// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: a2billing.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetAgentIdsByParentAgentIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId int32 `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
}

func (x *GetAgentIdsByParentAgentIDRequest) Reset() {
	*x = GetAgentIdsByParentAgentIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a2billing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentIdsByParentAgentIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdsByParentAgentIDRequest) ProtoMessage() {}

func (x *GetAgentIdsByParentAgentIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_a2billing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdsByParentAgentIDRequest.ProtoReflect.Descriptor instead.
func (*GetAgentIdsByParentAgentIDRequest) Descriptor() ([]byte, []int) {
	return file_a2billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetAgentIdsByParentAgentIDRequest) GetAgentId() int32 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type GetAgentIdsByParentAgentIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentIds []int32 `protobuf:"varint,1,rep,packed,name=agent_ids,json=agentIds,proto3" json:"agent_ids,omitempty"`
}

func (x *GetAgentIdsByParentAgentIDResponse) Reset() {
	*x = GetAgentIdsByParentAgentIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_a2billing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentIdsByParentAgentIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdsByParentAgentIDResponse) ProtoMessage() {}

func (x *GetAgentIdsByParentAgentIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_a2billing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdsByParentAgentIDResponse.ProtoReflect.Descriptor instead.
func (*GetAgentIdsByParentAgentIDResponse) Descriptor() ([]byte, []int) {
	return file_a2billing_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentIdsByParentAgentIDResponse) GetAgentIds() []int32 {
	if x != nil {
		return x.AgentIds
	}
	return nil
}

var File_a2billing_proto protoreflect.FileDescriptor

var file_a2billing_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x32, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x3e, 0x0a, 0x21,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x42, 0x79, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x22,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x42, 0x79, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x32,
	0x86, 0x01, 0x0a, 0x09, 0x41, 0x32, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x79, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x73, 0x42, 0x79, 0x50, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2c, 0x2e, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x73, 0x42, 0x79, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x73, 0x42, 0x79, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_a2billing_proto_rawDescOnce sync.Once
	file_a2billing_proto_rawDescData = file_a2billing_proto_rawDesc
)

func file_a2billing_proto_rawDescGZIP() []byte {
	file_a2billing_proto_rawDescOnce.Do(func() {
		file_a2billing_proto_rawDescData = protoimpl.X.CompressGZIP(file_a2billing_proto_rawDescData)
	})
	return file_a2billing_proto_rawDescData
}

var file_a2billing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_a2billing_proto_goTypes = []interface{}{
	(*GetAgentIdsByParentAgentIDRequest)(nil),  // 0: transport.GetAgentIdsByParentAgentIDRequest
	(*GetAgentIdsByParentAgentIDResponse)(nil), // 1: transport.GetAgentIdsByParentAgentIDResponse
}
var file_a2billing_proto_depIdxs = []int32{
	0, // 0: transport.A2billing.GetAgentIdsByParentAgentID:input_type -> transport.GetAgentIdsByParentAgentIDRequest
	1, // 1: transport.A2billing.GetAgentIdsByParentAgentID:output_type -> transport.GetAgentIdsByParentAgentIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_a2billing_proto_init() }
func file_a2billing_proto_init() {
	if File_a2billing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_a2billing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentIdsByParentAgentIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_a2billing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentIdsByParentAgentIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_a2billing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_a2billing_proto_goTypes,
		DependencyIndexes: file_a2billing_proto_depIdxs,
		MessageInfos:      file_a2billing_proto_msgTypes,
	}.Build()
	File_a2billing_proto = out.File
	file_a2billing_proto_rawDesc = nil
	file_a2billing_proto_goTypes = nil
	file_a2billing_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// A2BillingClient is the client API for A2Billing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type A2BillingClient interface {
	GetAgentIdsByParentAgentID(ctx context.Context, in *GetAgentIdsByParentAgentIDRequest, opts ...grpc.CallOption) (*GetAgentIdsByParentAgentIDResponse, error)
}

type a2BillingClient struct {
	cc grpc.ClientConnInterface
}

func NewA2BillingClient(cc grpc.ClientConnInterface) A2BillingClient {
	return &a2BillingClient{cc}
}

func (c *a2BillingClient) GetAgentIdsByParentAgentID(ctx context.Context, in *GetAgentIdsByParentAgentIDRequest, opts ...grpc.CallOption) (*GetAgentIdsByParentAgentIDResponse, error) {
	out := new(GetAgentIdsByParentAgentIDResponse)
	err := c.cc.Invoke(ctx, "/transport.A2billing/GetAgentIdsByParentAgentID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// A2BillingServer is the server API for A2Billing service.
type A2BillingServer interface {
	GetAgentIdsByParentAgentID(context.Context, *GetAgentIdsByParentAgentIDRequest) (*GetAgentIdsByParentAgentIDResponse, error)
}

// UnimplementedA2BillingServer can be embedded to have forward compatible implementations.
type UnimplementedA2BillingServer struct {
}

func (*UnimplementedA2BillingServer) GetAgentIdsByParentAgentID(context.Context, *GetAgentIdsByParentAgentIDRequest) (*GetAgentIdsByParentAgentIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentIdsByParentAgentID not implemented")
}

func RegisterA2BillingServer(s *grpc.Server, srv A2BillingServer) {
	s.RegisterService(&_A2Billing_serviceDesc, srv)
}

func _A2Billing_GetAgentIdsByParentAgentID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentIdsByParentAgentIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(A2BillingServer).GetAgentIdsByParentAgentID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transport.A2billing/GetAgentIdsByParentAgentID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(A2BillingServer).GetAgentIdsByParentAgentID(ctx, req.(*GetAgentIdsByParentAgentIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _A2Billing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transport.A2billing",
	HandlerType: (*A2BillingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAgentIdsByParentAgentID",
			Handler:    _A2Billing_GetAgentIdsByParentAgentID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "a2billing.proto",
}
